config/routes.rb
Rails.application.routes.draw do
  
  resources :cars
  match ':controller(/:action(/:id))', :via => [:get, :post]
  
  

  root 'cars#index'
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
  	@cars=Car.all
  end

  def show
  	@car=Car.find(params[:id])
  end

  def edit
  	@car=Car.find(params[:id])
  end

  def update
  	@car=Car.find(params[:id])
  	@car.update_attributes(car_params)
  	flash[:notice]="Record succesfully updated"
  	redirect_to(:action=>"show",:id=>@car.id)

  end

  def new
  	@car=Car.new
  end

  def create
  	@car=Car.new(car_params)
  	if @car.save
  		flash[:notice]="#{@car.make} #{@car.model} added"
  		redirect_to @car
  		
  	else
  		flash[:notice]="Something went wrong"
  		render :new

  	end
  end

  def delete
  	@car=Car.find(params[:id])
  end

  def destroy
  	@car=Car.find(params[:id])
  	@car.destroy
  end
  private
  def car_params
  	params.require(:car).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/delete.html.erb
<h1>Cars#delete</h1>
Gerçekten silmek istiyor musunuz?<br>
<%=@car.make+" "%><%=@car.model+" "%><%=@car.year %>
<%=link_to("Evet", {:action => "destroy", :id => @car.id}, :method=> :delete)%>
<br>
<%=link_to("Geri Dön", {:action => "index"})%>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p><%="#{@car.make} #{@car.model}"%> silindi.</p>
<%=link_to "Anasayfa'ya Dön", cars_path%>

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<%=link_to "Anasayfa'ya Dön", cars_path%>


<%= form_for @car, url: {action: "update"}, html: {class: "edit_form"} do |f| %>
  <p><%=label_tag("Marka")%><%= f.text_field :make %></p>
  <p><%=label_tag("Model")%><%= f.text_field :model %></p>
  <p><%=label_tag("Yıl")%><%= f.number_field :year, in: 1990..2004 %></p>
  <p><%=label_tag("Kapı Sayısı")%><%= f.number_field :doors_count, in: 2..7 %></p>
  <p><%=label_tag("VIN")%><%= f.text_field :vin %></p>
  <p><%=label_tag("Fiyat")%><%= f.text_field :price %></p>
  <p><%=label_tag("Durum")%><%=radio_button("car", "rented", "true")%><%=radio_button("car", "rented", "false")%></p>

  <p><%= f.submit "Düzenle" %></p>
<% end %>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<%=link_to "Yeni Kayıt", new_car_path%>
<%@cars.each do |c|%>
<p>
	<%=c.make%>
	<%=c.model%>
	<%=c.year%>
	<%=link_to("Detay", {:action=>"show", :id=>c.id}, :class=>"action show")%>
	<%=link_to("Sil", {:action=>"delete", :id=>c.id}, :class=>"action delete")%>
	<%=link_to("Düzenle", {:action=>"edit", :id=>c.id}, :class=>"action delete")%>


</p>
<%end%>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<%=link_to("Geri Dön", :action=>"index")%>
<p><% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %></p>

<%= form_for @car, url: {action: "create"}, html: {class: "new_form"} do |f| %>
  <p><%=label_tag("Marka")%><%= f.text_field :make %></p>
  <p><%=label_tag("Model")%><%= f.text_field :model %></p>
  <p><%=label_tag("Yıl")%><%= f.number_field :year, in: 1990..2004 %></p>
  <p><%=label_tag("Kapı Sayısı")%><%= f.number_field :doors_count, in: 2..7 %></p>
  <p><%=label_tag("VIN")%><%= f.text_field :vin %></p>
  <p><%=label_tag("Fiyat")%><%= f.text_field :price %></p>
  <p><%=label_tag("Durum")%><%=radio_button("car", "rented", "true")%><%=radio_button("car", "rented", "false")%></p>

  <p><%= f.submit "Oluştur" %></p>
<% end %>

app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p><% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %></p>
<%=link_to "Anasayfa'ya Dön", cars_path%>
<p><%=label_tag("Marka:")%><%=@car.make%></p>
<p><%=label_tag("Model:")%><%=@car.model%></p>
<p><%=label_tag("Yıl:")%><%=@car.year%></p>
<p><%=label_tag("Kapı Sayısı:")%><%=@car.doors_count%></p>
<p><%=label_tag("VIN:")%><%=@car.vin%></p>
<p><%=label_tag("Fiyat:")%><%=@car.price%></p>
<p><%=label_tag("Durum:")%><%=@car.rented%></p>
<p><%=link_to("Sil", {:action=>"delete", :id=>@car.id}, :class=>"action delete")%></p>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>